name: env-electron-python
channels:
  - defaults
  - conda-forge
dependencies:
<<<<<<< HEAD
  - python = 3.9
  - PyInstaller = 4.7
  - nodejs = 10.13.0
  - pywin32 = 303
  - git = 2.20.1
  - pip
  - pip:
      - chardet == 4.0.0
      - pandas == 1.4.2
      - openpyxl == 3.0.9
      - zerorpc == 0.6.3
      - pennsieve == 6.1.2
      - configparser == 4.0.2
      - python-docx == 0.8.10
      - xlrd == 2.0.1
      - biopython == 1.79
      - gevent == 21.12.0
      - protobuf == 3.20.0
=======
- python = 3.9
- nodejs = 10.13.0
- pywin32 = 303
- git = 2.20.1
- setuptools=58.0.4
- pip
- pip:
  - futures == 3.1.1
  - chardet == 4.0.0
  - pandas == 1.4.2
  - openpyxl == 3.0.9
  - pennsieve == 6.1.2
  - configparser == 4.0.2
  - python-docx == 0.8.10
  - xlrd == 2.0.1
  - biopython == 1.79
  - gevent == 21.12.0
  - flask == 2.0.2
  - flask_restx
  - protobuf == 3.20.0
  - PyInstaller == 4.7
>>>>>>> origin/flask-conversion-staging
