name: Build-and-deploy-mac
run-name: ${{ github.actor }} is building a MAC release for SODA

on:
  push:
    branches:
      - main

jobs:
  deploy-on-mac:
    runs-on: macos-11.0

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: env-electron-python
          environment-file: environment-MAC.yml
          auto-activate-base: false

      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install package.json modules and their dependencies
        run: npm install --ignore-scripts

      - name: Codesign executable
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 —decode > certificate.p12
          security create-keychain -p <your-password> build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p <your-password> build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k <your-password> build.keychain
          /usr/bin/codesign --force -s <identity-id> ./path/to/you/app -v

      - name: Build and deploy on MAC
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run python-onefile-build
          npm run build-mac
          npm run deploy-mac
