name: Build-and-deploy-mac
run-name: ${{ github.actor }} is building a mac release for SODA

on:
  push:
    branches:
      - main

jobs:
  deploy-on-mac:
    runs-on: macOS-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: env-electron-python
          environment-file: environment-Linux.yml
          auto-activate-base: false

      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install package.json modules and their dependencies
        run: npm install --ignore-scripts
