name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: env-electron-python
          environment-file: environment-Linux.yml
          auto-activate-base: false
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: s-weigand/setup-conda@v1
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: ls
      - run: npm install
      # get the npm version
      - run: npm --v
      - run: |
          npm run python-onefile-build
          npm run build-linux
