name: Build-and-deploy-linux
run-name: ${{ github.actor }} is building a linux release for SODA

on:
  push:
    branches:
      - main

jobs:
  deploy-on-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: env-electron-python
          environment-file: environment-Linux.yml
          auto-activate-base: false

      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Build and deploy on Linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          conda activate env-electron-python
          npm run python-onefile-build
          npm run build-linux
          npm run deploy-linux
