name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: s-weigand/setup-conda@v1
      - run: conda --version
      - run: which python
      - run: conda env create -f environment-Linux.yml
      - run: conda init bash
      - run: conda activate env-electron-python

      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: ls
      - run: npm install
      # get the npm version
      - run: npm --v
