name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: env-electron-python
          environment-file: environment-Linux.yml
          auto-activate-base: false

      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install --ignore-scripts
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        conda activate env-electron-python
        npm run python-onefile-build
        npm run build-linux
        npm run deploy-linux