name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v2
      - name: Set up Python 3.8
      with:
        python-version: 3.8

      - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment-Linux.yml --name base

      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: ls
      - run: npm install
      # get the npm version
      - run: npm --v
