name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10

      # Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm install
        working-directory: src

      - name: Run Prettier
        uses: wearerequired/lint-action@v1
        with:
          prettier: true
          prettier_dir: "./src"
          prettier_extensions: "css,html,js,json,jsx,md,sass,scss,ts,tsx,vue"
          auto_fix: true
          github_token: ${{ secrets.BOT_ACTIONS }}
          git_email: "fairdataihub@gmail.com"
          git_name: "fairdataihub-bot"

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install black
        run: pip install black

      - name: Run Black
        uses: wearerequired/lint-action@v1
        with:
          black: true
          black_dir: "./src/pysoda"
          auto_fix: true
          github_token: ${{ secrets.BOT_ACTIONS }}
          git_email: "fairdataihub@gmail.com"
          git_name: "fairdataihub-bot"
